Sprint 16
LyashenkoKV/Tracker pull request #3
Opened 2024-09-05 13:57 UTC by LyashenkoKV

Добавил PageVC и экран со списком категорий переписал на архитектуру MVVM

2024-09-05 14:51 UTC, Kirchberg commented on Tracker/CategoryVC/CategoryCell.swift
> +    override func configure(with text: String, showSwitch: Bool = false, isSwitchOn: Bool = false) {
Не передаем параметр `isSwitchOn`в `super.configure`

2024-09-05 14:54 UTC, Kirchberg commented on Tracker/CategoryVC/CategoryViewController.swift
> +        )
Было бы хорошо увидеть такие отступы:
```swift
viewModel = CategoryViewModel(
    trackerCategoryStore: TrackerCategoryStore(
        persistentContainer: CoreDataStack.shared.persistentContainer
    )
)
```

Или такой:
```swift
viewModel = CategoryViewModel(
    trackerCategoryStore: TrackerCategoryStore(persistentContainer: CoreDataStack.shared.persistentContainer)
)
```

2024-09-05 15:00 UTC, Kirchberg commented on Tracker/CategoryVC/CategoryViewController.swift
> +        print(categories)
Стоит вместо `print` использовать [OSLog](https://www.avanderlee.com/debugging/oslog-unified-logging/), он позволяет вынести такие сообщения на разные «уровни опасности» и является как таковой хорошей заменой `print`. Сами же `print` использовать можно, но рекомендуется только во время дебага, а перед отправлением на PR, просят убрать

2024-09-05 15:06 UTC, Kirchberg commented on Tracker/CategoryVC/CategoryViewController.swift
> +        )
`viewModel` стоит создавать при инициализации экрана, это позволит нам уйти от опциональности и не разворачивать модель в местах использования:
```swift
private let viewModel: CategoryViewModel = CategoryViewModel(
    trackerCategoryStore: TrackerCategoryStore(persistentContainer: CoreDataStack.shared.persistentContainer)
)
```

2024-09-05 15:17 UTC, Kirchberg commented on Tracker/CategoryVC/CategoryViewController.swift
> +        tableView.reloadData()
В данном случае нет необходимости делать `tableView.reloadData()`, поскольку вызов этой функции будет в `onCategoriesUpdated` после обновления категорий

2024-09-05 15:22 UTC, LyashenkoKV commented on Tracker/CategoryVC/CategoryCell.swift
> +    override func configure(with text: String, showSwitch: Bool = false, isSwitchOn: Bool = false) {
Понял)

2024-09-05 15:24 UTC, Kirchberg commented on Tracker/CategoryVC/CategoryViewController.swift
> +    }
Данный код будет исполнен на `main` потоке без написания `DispatchQueue.main.async`, было бы хорошо убрать

2024-09-05 15:25 UTC, Kirchberg commented on Tracker/CategoryVC/CategoryViewModel.swift
> +class CategoryViewModel: TrackerDataProvider {
Было бы хорошо проставлять ключевое слово `final` классам для ускорения работы компилятора. Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, что класс не планируется расширять наследованием. В таком случае комплятор будет быстрее находить адрес ячейки памяти при вызове функции.

Эта тема про диспетчеризацию, если интересно, можно почитать здесь:
https://habr.com/ru/post/673400/
https://habr.com/ru/company/simbirsoft/blog/673636/

2024-09-05 15:26 UTC, Kirchberg commented on Tracker/CategoryVC/CategoryViewModel.swift
> +            )
Использование отдельного логгера, молодец ✨

2024-09-05 15:27 UTC, Kirchberg commented on Tracker/CreatingTrackersVC/CreatingTrackerViewController.swift
> +                           section: TrackerSection.buttons.rawValue)],
Было бы хорошо поправить отступы

2024-09-05 15:29 UTC, Kirchberg commented on Tracker/MainVC/MainViewController.swift
> +        //CoreDataStack.shared.clearCoreData()
Закоментированный код стоит убрать, особенно, если он позже использоваться не будет

2024-09-05 15:30 UTC, Kirchberg commented on Tracker/MainVC/MainViewController.swift
> +        trackersViewController.configure(trackersPresenter as TrackersPresenterProtocol)
Приведение к типу `as TrackersPresenterProtocol` в данной строчке избыточно, необходимо удалить

2024-09-05 15:31 UTC, Kirchberg commented on Tracker/MainVC/MainViewController.swift
> +//}
Было бы хорошо убрать лишние строки, это позволит уменьшить количество строк. [Ссылка на одну из статей, которая рассказывает про проблемы лишних строк кода](https://habr.com/ru/articles/354750/)

2024-09-05 15:36 UTC, Kirchberg commented on Tracker/OnboardingVC/OnboardingHelper.swift
> +}
Было бы хорошо увидеть модель в таком виде:
```swift
struct OnboardingHelper {

    let greeting: String
    let image: UIImage

}
```

Данный вид больше используется, потому что

1. Обязательная инициализация:
   Поля должны быть заданы при создании объекта, что предотвращает ошибки.

2. Избегание пустых значений:
   В изначальном варианте строки будут пустыми, а изображения — по умолчанию, что не всегда правильно.

3. Ясность данных:
   Поля обязательны, что делает код более понятным и надежным.

2024-09-05 15:51 UTC, Kirchberg commented on Tracker/OnboardingVC/OnboardingPageViewController.swift
> +    private func addVC() {
Было бы хорошо назвать как `addPages` и сделать функцию с возвращением типа `OnboardingHelper`, то есть:
```swift
override func viewDidLoad() {
    ...
    pages = makePages()
    ...
}
```

2024-09-05 15:56 UTC, Kirchberg requested changes
Привет, оставил один критический комментарий, без него, к сожалению, я не могу принять работу, описал его в общем отзыве :(

Отличная работа, оставил несколько комментариев на улучшения и размышления, молодец ✨

2024-09-06 07:38 UTC, Kirchberg approved these changes
Все хорошо, больше критических комментариев нет, успехов в следующих заданиях 🎉

2024-09-06 13:54 UTC, merged